version: '3.9'

services:
    mysql:
        image: mysql:8.0
        restart: always
        container_name: hhplus-e-commerce
        ports:
            - '3307:3307'
        environment:
            MYSQL_ROOT_PASSWORD: root1234
            MYSQL_DATABASE: hhplus_e_commerce
            MYSQL_USER: ecommerce
            MYSQL_PASSWORD: root1234
        volumes:
            - /var/lib/mysql
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci

volumes:
    mysql_data:
