version: '3.8'

services:
    zookeeper:
        image: 'bitnami/zookeeper'
        ports:
            - '2181:2181'
        volumes:
            - 'zookeeper_data:/bitnami'
        environment:
            ALLOW_ANONYMOUS_LOGIN: yes
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 3000

    kafka:
        image: 'bitnami/kafka:latest'
        ports:
            - '9092:9092'
        volumes:
            - 'kafka_data:/bitnami'
        depends_on:
            - zookeeper
        environment:
            KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_CFG_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

    kafka-ui:
        image: provectuslabs/kafka-ui
        ports:
            - '8080:8080'
        restart: always
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

volumes:
    zookeeper_data:
        driver: local
    kafka_data:
        driver: local
