version: '3.8'

services:
    redis:
        image: redis
        ports:
            - 6379:6379
        command: redis-server --port 6379 --requirepass test1234
        volumes:
            - redis:/data

volumes:
    redis:
        driver: local
